version: '3'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge